Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "myubuntu.box"
  config.vm.network :private_network, ip: "192.168.0.42"
  config.vm.synced_folder "temp/", "/srv"
end
